### PR TITLE
mcclendon stuff

### PR DESCRIPTION
**Pull request by cxhernandez**
see http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2790287/#FD2

### CODE REVIEW

**Comment by cxhernandez** [comment]
@msultan: ^ this seems like a better way to correct for sampling bias

**Comment by msultan** [comment]
I don't understand that equation. Seems like if you have a lot of data in a particular bin, you want to subtract out some "stuff" from the entropy estimator but I wonder if that causes you to underestimate the entropy and add more noise to your analysis.

**Comment by cxhernandez** [comment]
For large bin values that equation turns into the vanilla entropy estimator. But I think that's where the "adaptive partitioning" comes in. Still need to implement that....

**Comment by msultan** [comment]
oh i see that now for large nij.

**Pull request merged**
